services:
  app:
    build:
      context: .
      dockerfile: web_server/Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www
    networks:
      - budgie-app

  web:
    image: nginx:alpine
    container_name: budgie-web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./web_server/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - budgie-app

  mysql:
    image: mysql:8.0
    container_name: budgie-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=budgie_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - budgie-app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: budgie-pma
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    networks:
      - budgie-app

  mailhog:
    image: mailhog/mailhog:latest
    container_name: budgie-mail
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - budgie-app

networks:
  budgie-app:

volumes:
  mysql_data: